name: 'Upload a Release Asset'
description: 'Upload release assets to a release in your repository'

inputs:
  upload_url:
    description: 'URL for uploading assets to the release'
  files:
    description: 'Files to upload'
    required: true
  github_token:
    description: 'Requires secrets.GITHUB_TOKEN to publish assets'
    required: true
  content_type:
    description: 'Content-type of the assets. https://www.iana.org/assignments/media-types/media-types.xhtml'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'package'
  color: 'gray-dark'
